In [1]:
import numpy as np
import random

In [2]:
#Initialisation for the different algorithms:
barcode1 = np.array([[0, 100.], [1.37, 94.2], [5.80, 86.], [18., 83.75], [42., 60.]])      # 24 permutations (1234)
barcode2 = np.array([[0., 100.], [1.37, 86.], [5.80, 94.2], [18., 83.75]])      # 3 permutations (213)
barcode3 = np.array([[0., 10.], [1., 9.], [2., 8.], [3., 7.], [4., 6.]])        # 24 perutations (1234)
barcodeE = np.array([[0., 10.], [9., 1.], [6., 5.], [5., 11.]])

#Choose your barcode:
barcode = barcode3
barcode_size = int(barcode.size/2)

In [3]:
#Tests:
error1 = 0; error2 = 0; error3 = 0

for n in range(barcode_size):
    if barcode[n][0] > barcode[n][1]:
        print ("error1: birth need to be lower than death")
        error1 = 1
    
for n in range(barcode_size - 1):
    if barcode[n][0] > barcode[n+1][0]:
        print("error2: we need a sorted by birth barcode.")
        error2 = 1

for n in range(barcode_size - 1):
    if barcode[n+1][1] > barcode[0][1]:
        print("error3: the first bar must contains all the others")
        error3 = 1

if error1 == 0 and error2 == 0 and error3 == 0 :
    print ("Tests: passed")    

Tests: passed


In [4]:
#Auto initialisation with in function of what was token:
matrix_adj = np.zeros((barcode_size, barcode_size))     #empty matrix.
matrix_pb = np.zeros((barcode_size, barcode_size))     #empty matrix.
matrix_real = np.zeros((barcode_size, barcode_size))    #empty matrix.
matrix_fr = np.zeros((barcode_size, barcode_size))    #empty matrix.

finit_support = barcode[0][1] - barcode[0][0]         #lifetime of bar 0.
proba = np.linspace(0, 0, barcode_size-1)             #list of all probabilities for each line (equi).
permutation_number = 1                                #Number of possible permutations for a barcode.
index = np.linspace(0, 0, barcode_size-1)             #equivalente class.

In [5]:
#Permutation Number:
for i in range(barcode_size)[1:]:
    for j in range(barcode_size)[:i]:
        if barcode[j][1] > barcode[i][1]:
            index[i-1] += 1
    permutation_number *= index[i-1]
    
#Equivalent Class:
for i in range(barcode_size - 1):
    index[i] = index[i] - (i+1)        #To know which of them are already in the right order.
clock = 1
while(clock < barcode_size):
    min = 1000
    memory = 0
    for j in range(barcode_size - 1):
        if index[j] < min:
            min = index[j]
            memory = j
    index[memory] = clock
    clock += 1

In [6]:
#Matrix initialisation:

#Probability Matrix:
for i in range(barcode_size):
    for j in range(barcode_size)[i+1:]:
        if barcode[i][1] > barcode[j][1]:
            matrix_pb[j][i] = 1
for x in range(barcode_size)[1:]:
    clock = 0
    for y in range(barcode_size)[:x]:
        clock += matrix_pb[x][y]             #number of 1 on a single line
    probability = 1./clock                   #normalisation for equiprobability
    for z in range(barcode_size)[:x]:
        if matrix_pb[x][z] == 1:
            matrix_pb[x][z] = probability

#Adjacency Matrix:
for k in range(barcode_size):
    matrix_adj[k][k] = barcode[k][0]             
for l in range(barcode_size):
    for m in range(barcode_size)[l+1:]:
        if barcode[l][1] > barcode[m][1]:
            matrix_adj[m][l] = barcode[m][1]


In [8]:
#Possible realisation
for n in range(1000):
    #Real Matrix
    for k in range(barcode_size):
        matrix_real[k][k] = matrix_adj[k][k]   
    for i in range(barcode_size)[1:]:
        clock = 0
        for j in range(barcode_size)[:i]:
            if matrix_pb[i][j] != 0:
                clock += 1
        if clock != 0:
            probability = 1./clock
        else:
            probability = 0.
        proba[i-1] = probability
        complete = False
        nbr = random.random()
        for j in range(barcode_size)[:i]:
            if (nbr < ((j+1)*proba[i-1]) and (not complete)):
                matrix_real[i][j] = matrix_adj[i][j]
                complete = True
            else:
                matrix_real[i][j] = 0
    for o in range(barcode_size)[1:]:
        for p in range(barcode_size)[:o]:
            if matrix_real[o][p] != 0:
                matrix_fr[o][p] += 1

#Normalisation of frequency matrix:
for i in range(barcode_size)[1:]:
    sum = 0
    for j in range(barcode_size)[:i]:
        sum += matrix_fr[i][j]
    for j in range(barcode_size)[:i]:
        matrix_fr[i][j] = matrix_fr[i][j]/sum

print("All possible matrices are in the form: \n", matrix_adj, "\n")
print("The last matrix realised was: \n", matrix_real, "\n")
print("The Probability matrix is: \n", matrix_pb, "\n")
print("The Frequency matrix over 1000 realisations is: \n", matrix_fr, "\n")

All possible matrices are in the form: 
 [[0. 0. 0. 0. 0.]
 [9. 1. 0. 0. 0.]
 [8. 8. 2. 0. 0.]
 [7. 7. 7. 3. 0.]
 [6. 6. 6. 6. 4.]] 

The last matrix realised was: 
 [[0. 0. 0. 0. 0.]
 [9. 1. 0. 0. 0.]
 [0. 8. 2. 0. 0.]
 [0. 0. 7. 3. 0.]
 [6. 0. 0. 0. 4.]] 

The Probability matrix is: 
 [[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.5        0.5        0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.         0.        ]
 [0.25       0.25       0.25       0.25       0.        ]] 

The Frequency matrix over 1000 realisations is: 
 [[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.480005   0.519995   0.         0.         0.        ]
 [0.33797403 0.36098202 0.30104396 0.         0.        ]
 [0.27396004 0.268001   0.23001998 0.22801898 0.        ]] 

